export const REQUEST_MESSAGES = "REQUEST_MESSAGES";
export const REQUEST_SUCCESS_MESSAGES = "REQUEST_SUCCESS_MESSAGES";
export const REQUEST_FAIL_MESSAGES = "REQUEST_FAIL_MESSAGES";

export const REQUEST_MESSAGES_STATUS = "REQUEST_MESSAGES_STATUS";
export const REQUEST_SUCCESS_MESSAGES_STATUS = "REQUEST_SUCCESS_MESSAGES_STATUS";
export const REQUEST_FAIL_MESSAGES_STATUS = "REQUEST_FAIL_MESSAGES_STATUS";

export const UPDATE_MESSAGE_TRACK = "UPDATE_MESSAGE_TRACK";
export const UPDATE_MESSAGE_SUCCES_TRACK = "UPDATE_MESSAGE_SUCCES_TRACK";